-- Unstructured text for RAG: documents and their embedded chunks (pgvector).
--
-- pgvector adds a `vector(n)` column type and distance operators:
--   <=> cosine distance (1 - cosine similarity), <-> L2, <#> negative inner product.
-- We use cosine: bge embeddings are compared by angle, not length.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE documents (
    regulation   text        NOT NULL,
    doc_id       text        NOT NULL,  -- "showdown:move:earthquake", "notes:stat-points"
    title        text        NOT NULL,
    doc_type     text        NOT NULL,
    source       text        NOT NULL,  -- key in pokechamp.sources.SOURCES
    license      text        NOT NULL,
    ref          text        NOT NULL,  -- where in the source it came from (for citations)
    retrieved_at timestamptz NOT NULL,
    metadata     jsonb       NOT NULL DEFAULT '{}',
    run_id       bigint      NOT NULL REFERENCES ingestion_runs (id),
    PRIMARY KEY (regulation, doc_id)
);

CREATE TABLE chunks (
    regulation      text         NOT NULL,
    chunk_id        text         NOT NULL,  -- f"{doc_id}#{index}"
    doc_id          text         NOT NULL,
    chunk_index     smallint     NOT NULL,
    heading         text         NOT NULL,
    text            text         NOT NULL,
    word_count      smallint     NOT NULL,
    content_hash    text         NOT NULL,
    embedding_model text         NOT NULL,  -- vectors from different models aren't comparable
    embedding       vector(384)  NOT NULL,  -- bge-small-en-v1.5 dimension
    -- Keyword-search column for phase 4's hybrid retrieval. Generated by
    -- Postgres from `text`, so it can never drift out of sync.
    tsv             tsvector GENERATED ALWAYS AS (to_tsvector('english', heading || ' ' || text)) STORED,
    run_id          bigint       NOT NULL REFERENCES ingestion_runs (id),
    PRIMARY KEY (regulation, chunk_id),
    FOREIGN KEY (regulation, doc_id) REFERENCES documents (regulation, doc_id) ON DELETE CASCADE
);

-- HNSW: an approximate-nearest-neighbour graph index. Queries hop through a
-- layered graph instead of comparing against every row: much faster at scale,
-- at the cost of (tunable) recall. At our size (~1k chunks) an exact scan would
-- also be fine; we build the index anyway because it's what production uses
-- and its recall vs an exact scan is something phase 4 can measure.
-- m / ef_construction are pgvector's defaults, spelled out to be explicit.
CREATE INDEX chunks_embedding_hnsw ON chunks
    USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

CREATE INDEX chunks_tsv_gin ON chunks USING gin (tsv);
